const SET_USER = 'SET_USER';
const SET_EMPTY_ROOMS = 'SET_EMPTY_ROOMS';
const SET_ROOM = 'SET_ROOM';
const SET_ME_BOOKINGS = 'SET_ME_BOOKINGS';
const SET_ROOMS = 'SET_ROOMS';
const SET_ROOM_BOOKINGS_FOR_ROOM = 'SET_ROOM_BOOKINGS_FOR_ROOM';

export const ACTION_TYPE = {
	SET_USER,
	SET_EMPTY_ROOMS,
	SET_ROOM,
	SET_ME_BOOKINGS,
	SET_ROOMS,
	SET_ROOM_BOOKINGS_FOR_ROOM
};
