const SET_USER = 'SET_USER';
const SET_EMPTY_ROOMS = 'SET_EMPTY_ROOMS';
const SET_ROOM = 'SET_ROOM';
const SET_ME_BOOKINGS = 'SET_ME_BOOKINGS';
const SET_ROOMS = 'SET_ROOMS';
const SET_BOOKINGS = 'SET_BOOKINGS_FOR_ROOM';
const UPDATE_BOOKING = 'UPDATE_BOOKING';
const ADD_ME_BOOKING = 'ADD_ME_BOOKING';

export const ACTION_TYPE = {
	SET_USER,
	SET_EMPTY_ROOMS,
	SET_ROOM,
	SET_ME_BOOKINGS,
	SET_ROOMS,
	SET_BOOKINGS,
	UPDATE_BOOKING,
	ADD_ME_BOOKING
};
