const SET_USER = 'SET_USER';
const SET_EMPTY_ROOMS = 'SET_EMPTY_ROOMS';
const SET_ROOM = 'SET_ROOM';
const SET_ME_BOOKINGS = 'SET_ME_BOOKINGS';

export const ACTION_TYPE = {
	SET_USER,
	SET_EMPTY_ROOMS,
	SET_ROOM,
	SET_ME_BOOKINGS
};
